rails/config/routes.rb
Rails.application.routes.draw do
  scope module: 'user', constraints: ->(req) { Context.get_context(req) == :user }, name_path: 'user', as: 'user' do
    root to: 'welcome#index'
    match '/', to: 'welcome#index', via: :all
    match '/search', to: 'welcome#search', via: :all
    match '/recommended-products', to: 'welcome#recommended_products', via: :get
    match '/login', to: 'sessions#login', via: %i[post get]
    match '/register', to: 'sessions#register', via: %i[post get]
    get '/auth/:provider/callback', to: 'sessions#create'
    get '/auth/failure', to: 'sessions#failure'
    match '/recover-account', to: 'sessions#recover_account', via: :get
    match '/confirm-email', to: 'sessions#confirm_email', via: :get
    match '/request-password-reset', to: 'sessions#request_password_reset', via: :get
    match '/logout', to: 'sessions#logout', via: :all
    match '/contact', to: 'welcome#contact', via: :post
    match '/chat/send_message', to: 'chat_bot#send_message', via: :post
    match '/add_goal', to: 'welcome#add_goal', via: :post
    match '/update_goal', to: 'welcome#update_goal', via: :post

    resource :profile, only: %i[show index] do
      match :user, on: :collection, via: %i[get put]
      match :account, on: :collection, via: %i[get put]
      match :dietary_preferences, on: :collection, via: %i[get put]
      match :notifications, on: :collection, via: %i[get]
      match :billing, on: :collection, via: %i[get]
      match :get_plus, on: :collection, via: %i[get]
      match :cancel_plus, on: :collection, via: %i[delete]
    end

    resources :notifications, only: %i[destroy]

    resource :basket

    resources :diaries do
      put :remove_from_user_diary, on: :collection
      post :add_to_user_diary, on: :collection
      put :modify_user_diary, on: :collection
    end

    resources :allergens, only: %i[index show] do
      get :search, on: :collection
    end

    resources :products do
      patch :add_to_favorites, on: :member
      patch :remove_from_favorites, on: :member
      match :create_product, on: :collection, via: %i[get post]
      get :products_selection, on: :collection
      get :search_by_ean, on: :collection
      get :search, on: :collection
      resources :reviews
    end

    resources :submissions, only: %i[index show]
    get '/upload/grid/*path', to: 'gridfs#serve'

    namespace :hub do
      get '/', to: 'hub#index'
      get 'following', to: 'hub#following'
      get 'hashtag/:hashtag', to: 'hub#hashtag'
      get 'for_you', to: 'hub#for_you'
      resources :posts, only: %i[show new create]
      post 'posts/:id/report', to: 'posts#report'
      post 'posts/:post_id/rating', to: 'ratings#create'
      delete 'posts/:post_id/rating', to: 'ratings#destroy'
      post 'posts/:id/award', to: 'posts#award'
      resources :users, only: %i[show] do
        get '/follow', to: 'users#follow'
        get '/followers', to: 'users#followers'
        get '/following', to: 'users#following'
      end
    end
  end

  scope module: 'admin', constraints: ->(req) { Context.get_context(req) == :admin }, name_path: 'admin', as: 'admin' do
    root to: 'submissions#index'
    match '/', to: 'welcome#index', via: :all

    match '/login', to: 'sessions#login', via: %i[post get]
    match '/logout', to: 'sessions#logout', via: %i[post]

    resources :submissions
    resources :posts do
      delete :ignore_post, on: :member
      delete :cleanse_reports, on: :member
    end

    resources :products do
      put :approve, on: :member
      put :reject, on: :member
    end

    resources :feedback_messages, only: %i[index] do
      patch :mark_as_read, on: :member
    end
  end
end

rails/app/views/partials/layout/_footer.html.haml
.flex.flex-col.w-full.justify-between.space-y-4.bg-primary-500.p-8.text-white{ class:"md:flex-row md:space-x-4 space-y-0" }
  .flex.flex-col.items-center.justify-center.space-y-2.w-full
    %span
      = "Copyright © #{Time.now.year} Freshly. All rights reserved."
    .flex.flex-row.items-center.space-x-2
      %span
        = "Powered by Ruby on Rails"
      .mdi.mdi-language-ruby-on-rails.text-2xl
    .flex.flex-col.items-center.w-full
      .font-bold.text-s.text-slate-100.mb-3
        = "Contributors"
      %div.flex.flex-col.grid.gap-x-4.items-center.ml-20{class:"grid-cols-2"}
        %span.text-xs.text-slate-100.flex
          = "Mihai Soare"
        %a(href="https://www.linkedin.com/in/m-a-soare/" target="_blank" rel="noopener noreferrer")
          %span.mdi.mdi-linkedin.text-base{ class: "w-1/4 hover:text-indigo-300" }
        %span.text-xs.text-slate-100.flex
          = "Robert Popa"
        %a(href="https://www.linkedin.com/in/ra-popa/" target="_blank" rel="noopener noreferrer")
          %span.mdi.mdi-linkedin.text-base{ class: "w-1/4 hover:text-indigo-300" }
        %span.text-xs.text-slate-100.flex
          = "Vlad Mihaescu"
        %a(href="https://www.linkedin.com/in/vlad-mihaescu/" target="_blank" rel="noopener noreferrer")
          %span.mdi.mdi-linkedin.text-base{ class: "w-1/4 hover:text-indigo-300" }
  .flex.flex-col.items-center.w-full.space-y-4
    .font-bold
      = "Credits"
    = link_to "https://world.openfoodfacts.org/", target: "_blank" do
      = image_tag "https://static.openfoodfacts.org/images/logos/off-logo-horizontal-light.svg", class: "w-40 h-8"
    = link_to "https://rapidapi.com/", target: "_blank" do
      = image_tag "https://rapidapi.com/static-assets/default/dark-logo-78e48dc1-ca3f-4d67-a6f5-74032f439c8b.svg", class: "w-40 h-6"
    = link_to "https://www.tailwindcss.com/", target: "_blank" do
      = image_tag "https://tailwindcss.com/_next/static/media/tailwindcss-logotype-white.944c5d0ef628083bb316f9b3d643385c86bcdb3d.svg", class: "w-40 h-8"
  .flex.flex-col.items-center.w-full.space-y-4
    .font-bold.w-full.text-center
      = "Contact Us"
    = controlled_form '/contact', method: :post, class: "flex flex-col gap-2 w-full max-w-2xl", id: "contact-form" do
      .flex.flex-col.items-center.space-y-2.w-full
        .flex.flex-row.items-center.space-x-2.w-full
          %div.relative.flex.items-center.w-full
            %i.mdi.mdi-email-outline.absolute.ml-2.text-gray-400.text-xl
            %input{type: "email", name: "email", id: "email", required: true, class: "pl-10 pr-3 py-2 border rounded-md w-full text-black", placeholder: "Email", required: true}
          %div.relative.flex.items-center.w-full
            %i.mdi.mdi-account-outline.absolute.ml-2.text-gray-400.text-xl
            %input{type: "text", name: "name", id: "name", required: true, class: "pl-10 pr-3 py-2 border rounded-md w-full text-black", placeholder: "Name", required: true}
        %textarea{ name: "message", id: "message", class: "rounded-lg p-2 w-full text-black", placeholder: "Message", required: true }
        %button{ class: "!bg-primary-400 text-white rounded-lg p-2 w-full", type: "submit", id: "contact-submit" }
          = "Send"

:javascript
  $(document).ready(function() {
    $('#contact-form').submit(function(e) {
      $('#email').val('');
      $('#name').val('');
      $('#message').val('');
    });
  });

rails/app/views/partials/layout/_header.html.haml
- links = [{ icon: "home-outline", label: "home", path: user_root_path },
           { icon: "forum-outline", label: "hub", path: "/hub" },
           { icon: "cart-outline", label: "Basket", path: user_basket_path },
           { icon: "notebook-multiple", label: "Diary", path: user_diaries_path }]

- content_for :head do
  = stylesheet_link_tag "layout/header"

%header.bg-primary-500.p-4.text-white.sm:block.z-50
  %nav.container.mx-auto.h-8.px-2.flex.justify-center.items-center.gap-10
    = link_to '/' do
      = image_tag "logo.png", class: "h-36"
    .hidden.sm:block.flex-1.rounded-full.text-black.text-sm
      = text_field_tag :search, nil, class: "search-autocomplete w-full p-2 rounded-lg", placeholder: "Search for a food item", type: "text"

    %ul.hidden.sm:flex.items-center.gap-4
      - links.each do |link|
        %li
          = link_to link[:path], class: "flex items-center gap-1" do
            %i.mdi.text-2xl{ class: "mdi-#{link[:icon]}" }

            %span.hidden.text-sm.capitalize.lg:inline-block
              = link[:label]
    #profile-section.hidden.sm:flex.items-center.h-full.gap-4.relative
      - if current_user.present?
        %span#notifications-section
          = link_to notifications_user_profile_path do
            %i.mdi.mdi-bell-outline.text-2xl
          = render "partials/layout/header/notifications_dropdown"
      %span#settings-section
        = link_to user_profile_path, id: 'profile-path' do
          - if current_user.present? and current_user.profile_picture.present?
            %img.w-8.h-8.rounded-full{ src: current_user.profile_picture_url }
          - else
            %i.mdi.mdi-account-circle-outline.text-2xl
        = render "partials/layout/header/profile_dropdown"

:javascript
  $(document).ready(function() {
    var updateLink = function() {
      var profileLink = document.getElementById("profile-path");
      if (window.innerWidth < 768) {
        profileLink.setAttribute('href', "#{user_profile_path}");
      } else {
        profileLink.setAttribute('href', "#{user_user_profile_path}");
      }
    };

    updateLink();

    window.addEventListener('resize', updateLink);

    $('.search-autocomplete').autocomplete({
      source: '/products/search',
      minLength: 2,
      delay: 500,
      autoFocus: true,
      focus: function(event, ui) {
        event.preventDefault();
      },
      select: function(event, ui) {
        event.preventDefault();
        window.location.href = ui.item.value;
        $(this).val(ui.item.label);
      }
    });


  });

  $(document).on('click', '[id^="notification-"]', function() {
    window.location.href = $(this).attr("href")
  })

  $(document).on("click", '[id^="close-notification-"]', function(e) {
    e.stopPropagation()
    $.ajax({
      url: $(this).attr("href"),
      method: "DELETE",
      success: function() {
        location.reload()
      },
      error: function() {
        console.error("Error deleting notification")
      }
    });
  });

rails/app/views/partials/layout/_mobile_nav.html.haml
- links = [{ icon: 'home-outline', path: user_root_path },
 { icon: 'magnify', path: '/search' },
 { icon: 'qrcode-scan', path: create_product_user_products_path },
 { icon: 'forum-outline', path: "/hub" },
 { icon: 'account-circle-outline', path: "/profile" }]

%footer.bg-primary-500.p-2.sm:hidden
  %nav
    %ul.flex.justify-around.items-center
      - links.each do |link|
        %li.grid.place-items-center
          = link_to link[:path], class: (link[:path] == "/" ? (request.path == "/" ? "text-primary-300" : "text-white") : (request.path.include?(link[:path]) ? "text-primary-300" : "text-white")) do
            .mdi.text-2xl{ class: "mdi-#{link[:icon]}" }