rails/config/routes.rb
Rails.application.routes.draw do
  scope module: 'user', constraints: ->(req) { Context.get_context(req) == :user }, name_path: 'user', as: 'user' do
    root to: 'welcome#index'
    match '/', to: 'welcome#index', via: :all
    match '/search', to: 'welcome#search', via: :all
    match '/recommended-products', to: 'welcome#recommended_products', via: :get
    match '/login', to: 'sessions#login', via: %i[post get]
    match '/register', to: 'sessions#register', via: %i[post get]
    get '/auth/:provider/callback', to: 'sessions#create'
    get '/auth/failure', to: 'sessions#failure'
    match '/recover-account', to: 'sessions#recover_account', via: :get
    match '/confirm-email', to: 'sessions#confirm_email', via: :get
    match '/request-password-reset', to: 'sessions#request_password_reset', via: :get
    match '/logout', to: 'sessions#logout', via: :all
    match '/contact', to: 'welcome#contact', via: :post
    match '/chat/send_message', to: 'chat_bot#send_message', via: :post
    match '/add_goal', to: 'welcome#add_goal', via: :post
    match '/update_goal', to: 'welcome#update_goal', via: :post

    resource :profile, only: %i[show index] do
      match :user, on: :collection, via: %i[get put]
      match :account, on: :collection, via: %i[get put]
      match :dietary_preferences, on: :collection, via: %i[get put]
      match :notifications, on: :collection, via: %i[get]
      match :billing, on: :collection, via: %i[get]
      match :get_plus, on: :collection, via: %i[get]
      match :cancel_plus, on: :collection, via: %i[delete]
    end

    resources :notifications, only: %i[destroy]

    resource :basket

    resources :diaries do
      put :remove_from_user_diary, on: :collection
      post :add_to_user_diary, on: :collection
      put :modify_user_diary, on: :collection
    end

    resources :allergens, only: %i[index show] do
      get :search, on: :collection
    end

    resources :products do
      patch :add_to_favorites, on: :member
      patch :remove_from_favorites, on: :member
      match :create_product, on: :collection, via: %i[get post]
      get :products_selection, on: :collection
      get :search_by_ean, on: :collection
      get :search, on: :collection
      resources :reviews
    end

    resources :submissions, only: %i[index show]
    get '/upload/grid/*path', to: 'gridfs#serve'

    namespace :hub do
      get '/', to: 'hub#index'
      get 'following', to: 'hub#following'
      get 'hashtag/:hashtag', to: 'hub#hashtag'
      get 'for_you', to: 'hub#for_you'
      resources :posts, only: %i[show new create]
      post 'posts/:id/report', to: 'posts#report'
      post 'posts/:post_id/rating', to: 'ratings#create'
      delete 'posts/:post_id/rating', to: 'ratings#destroy'
      post 'posts/:id/award', to: 'posts#award'
      resources :users, only: %i[show] do
        get '/follow', to: 'users#follow'
        get '/followers', to: 'users#followers'
        get '/following', to: 'users#following'
      end
    end
  end

  scope module: 'admin', constraints: ->(req) { Context.get_context(req) == :admin }, name_path: 'admin', as: 'admin' do
    root to: 'submissions#index'
    match '/', to: 'welcome#index', via: :all

    match '/login', to: 'sessions#login', via: %i[post get]
    match '/logout', to: 'sessions#logout', via: %i[post]

    resources :submissions
    resources :posts do
      delete :ignore_post, on: :member
      delete :cleanse_reports, on: :member
    end

    resources :products do
      put :approve, on: :member
      put :reject, on: :member
    end

    resources :feedback_messages, only: %i[index] do
      patch :mark_as_read, on: :member
    end
  end
end

rails/app/views/layouts/admin_application.html.haml
%html
  %head
    %title Freshly Admin
    %meta{name: "viewport", content: "width=device-width,initial-scale=1"}
  = csrf_meta_tags
  = csp_meta_tag
  = javascript_pack_tag 'application'
  = stylesheet_link_tag "application", "data-turbo-track" => "reload"
  = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track" => "reload"
  = stylesheet_link_tag "notifier/hidden"
  %script{src: "https://code.jquery.com/jquery-3.6.0.min.js"}
  %script{src: "https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"}
  %link{rel: "stylesheet", href: "https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css"}

  = yield :head

  %link{href: "https://cdn.materialdesignicons.com/7.4.47/css/materialdesignicons.min.css", rel: "stylesheet"}

  = javascript_importmap_tags

  %body.w-full.h-full.bg-slate-200.flex.flex-col
    = render "partials/notifier/success_notifier"
    = render "partials/notifier/error_notifier"

    %header.bg-primary-500.p-4.text-white
      %nav.container.mx-auto.h-8.flex.justify-between.items-center
        .font-bold.flex.flex-col.items-center
          %h1.text-lg.uppercase
            Freshly
          .text-sm
            Admin
        - if current_login.present?
          .flex.flex-row.items-center.justify-center.gap-4
            = link_to admin_posts_path, class: "flex items-center gap-1" do
              %i.mdi.text-2xl{ class: "mdi-forum-outline" }
              %span.text-sm.capitalize
                Hub posts
            = link_to admin_submissions_path, class: "flex items-center gap-1" do
              %i.mdi.text-2xl{ class: "mdi-clipboard-list-outline" }
              %span.text-sm.capitalize
                Submissions
            = link_to admin_feedback_messages_path, class: "flex items-center gap-1" do
              %i.mdi.text-2xl{ class: "mdi-email-outline" }
              %span.text-sm.capitalize
                Feedback
            #profile-section.hidden.sm:flex.items-center.h-full.gap-4.relative
              %i.mdi.mdi-account-circle-outline.text-2xl
              .dropdown-menu.absolute.top-full.-right-5.p-4.hidden
                .w-64.py-4.bg-primary-500.flex.flex-col.duration-300.gap-4.rounded-b-lg
                  .flex.flex-row.justify-between.items-center.px-4.text-2xl
                    = current_login.username
                    = link_to '/logout', method: :post do
                      %i.mdi.mdi-logout-variant

    %main.flex-1.p-4
      = yield

rails/app/views/layouts/user_application.html.haml
%html
  %head
  %title Freshly
  %meta{name: "viewport", content: "width=device-width,initial-scale=1"}
  = csrf_meta_tags
  = csp_meta_tag
  = javascript_pack_tag 'application'
  = stylesheet_link_tag "application", "data-turbo-track" => "reload"
  %link{href: "https://cdn.jsdelivr.net/npm/daisyui@4.10.1/dist/full.min.css", rel: "stylesheet", type: "text/css"}
  = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track" => "reload"
  = stylesheet_link_tag "notifier/hidden"
  %script{src: "https://code.jquery.com/jquery-3.6.0.min.js"}
  %script{src: "https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"}
  %script{src: "https://unpkg.com/@zxing/library@latest"}
  %link{rel: "stylesheet", href: "https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css"}

  = yield :head

  %link{href: "https://cdn.materialdesignicons.com/7.4.47/css/materialdesignicons.min.css", rel: "stylesheet"}
  %link{href: "https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap", rel: "stylesheet"}

  = javascript_importmap_tags

  %body.w-screen.h-svh.flex.flex-col.overflow-hidden
    = render "partials/notifier/success_notifier"
    = render "partials/notifier/error_notifier"
    = render "partials/layout/header"
    %main.flex.flex-col.flex-1.overflow-y-auto.overflow-x-hidden.min-h-0
      .flex-1
        = content_for?(:content) ? yield(:content) : yield
      = render "partials/layout/footer"
    - if current_user.present? and current_user.has_membership?
      = render "partials/chat_bot"
    = render "partials/layout/mobile_nav"

rails/app/views/layouts/user_hub.html.haml
- content_for :content do
  .container.mx-auto.p-4.max-w-2xl.flex.flex-col.items-center.gap-6
    .flex.w-full.shadow-md.rounded-lg.overflow-hidden
      %a.text-xl.py-3.cursor-pointer.text-center{class: "hover:bg-slate-100 w-1/2 " + (current_page?(user_hub_following_path) ? "bg-slate-300" : "bg-white"), href: user_hub_following_path}
        Following
      %a.text-xl.py-3.cursor-pointer.text-center{class: "hover:bg-slate-100 w-1/2 " + (current_page?(user_hub_for_you_path) ? "bg-slate-300" : "bg-white"), href: user_hub_for_you_path}
        For you
    %a.flex.items-center.gap-1.justify-center.w-full.py-3.shadow-md.rounded-lg.bg-white.cursor-pointer.text-xl{class: "hover:bg-slate-100", href: new_user_hub_post_path}
      %span
        Say something
      %span.mdi.mdi-chat-plus-outline.text-2xl
    = yield

= render template: "layouts/user_application"

rails/app/views/layouts/user_profile.html.haml
- unless @links.empty?
  - content_for :content do
    .size-full{class: "sm:mx-auto sm:px-8 sm:max-w-5xl px-4 py-2 sm: py-0"}
      .size-full{class: "flex flex-col justify-center gap-4"}
        #profile-settings-msg.hidden.flex.flex-col.justify-center.items-center.w-full{class: "sm:block"}
          .rounded-lg.p-2.w-fit{class: "backdrop-blur-[2px]"}
            .text-2xl.font-bold
              = 'Profile Settings'
            .text-gray-500.font-semibold.text-lg
              = 'Change your profile and account settings.'
        .size-full{ class: "shadow-lg bg-white rounded-lg flex p-4 sm:h-96 sm:flex-row sm:space-x-8 space-y-0" }
          .hidden{class: "sm:flex sm:justify-between sm:flex-col sm:border-r sm:pr-4"}
            .tabs.flex.gap-4{ class: "flex-col max-[600px]:overflow-x-auto" }
              - @links.each do |link|
                = link_to link[:href], class: 'flex items-center w-full' + " text-#{current_page?(link[:href]) ? 'primary-500' : 'black'} #{link[:md] == false ? "hidden" : ""}" do
                  %span.mdi.text-2xl.mr-2{class: "mdi-#{link[:icon]}"}
                  %span= link[:text]
            %div
              = link_to "/logout", method: :post, class: "flex flex-row items-center" do
                %i.mdi.mdi-logout-variant.text-2xl.mr-2
                %span Logout
          .size-full
            = yield
- else
  - content_for :content do
    .size-full{class: "sm:mx-auto sm:px-8 sm:max-w-2xl"}
      .size-full{class: "flex flex-col justify-center gap-4"}
        .size-full{ class: "sm:shadow-lg sm:bg-white sm:rounded-lg sm:flex sm:p-4 sm:h-96 sm:flex-row sm:space-x-8 sm:space-y-0" }
          .size-full
            = yield

= render template: "layouts/user_application"