rails/config/routes.rb
Rails.application.routes.draw do
  scope module: 'user', constraints: ->(req) { Context.get_context(req) == :user }, name_path: 'user', as: 'user' do
    root to: 'welcome#index'
    match '/', to: 'welcome#index', via: :all
    match '/search', to: 'welcome#search', via: :all
    match '/recommended-products', to: 'welcome#recommended_products', via: :get
    match '/login', to: 'sessions#login', via: %i[post get]
    match '/register', to: 'sessions#register', via: %i[post get]
    get '/auth/:provider/callback', to: 'sessions#create'
    get '/auth/failure', to: 'sessions#failure'
    match '/recover-account', to: 'sessions#recover_account', via: :get
    match '/confirm-email', to: 'sessions#confirm_email', via: :get
    match '/request-password-reset', to: 'sessions#request_password_reset', via: :get
    match '/logout', to: 'sessions#logout', via: :all
    match '/contact', to: 'welcome#contact', via: :post
    match '/chat/send_message', to: 'chat_bot#send_message', via: :post
    match '/add_goal', to: 'welcome#add_goal', via: :post
    match '/update_goal', to: 'welcome#update_goal', via: :post

    resource :profile, only: %i[show index] do
      match :user, on: :collection, via: %i[get put]
      match :account, on: :collection, via: %i[get put]
      match :dietary_preferences, on: :collection, via: %i[get put]
      match :notifications, on: :collection, via: %i[get]
      match :billing, on: :collection, via: %i[get]
      match :get_plus, on: :collection, via: %i[get]
      match :cancel_plus, on: :collection, via: %i[delete]
    end

    resources :notifications, only: %i[destroy]

    resource :basket

    resources :diaries do
      put :remove_from_user_diary, on: :collection
      post :add_to_user_diary, on: :collection
      put :modify_user_diary, on: :collection
    end

    resources :allergens, only: %i[index show] do
      get :search, on: :collection
    end

    resources :products do
      patch :add_to_favorites, on: :member
      patch :remove_from_favorites, on: :member
      match :create_product, on: :collection, via: %i[get post]
      get :products_selection, on: :collection
      get :search_by_ean, on: :collection
      get :search, on: :collection
      resources :reviews
    end

    resources :submissions, only: %i[index show]
    get '/upload/grid/*path', to: 'gridfs#serve'

    namespace :hub do
      get '/', to: 'hub#index'
      get 'following', to: 'hub#following'
      get 'hashtag/:hashtag', to: 'hub#hashtag'
      get 'for_you', to: 'hub#for_you'
      resources :posts, only: %i[show new create]
      post 'posts/:id/report', to: 'posts#report'
      post 'posts/:post_id/rating', to: 'ratings#create'
      delete 'posts/:post_id/rating', to: 'ratings#destroy'
      post 'posts/:id/award', to: 'posts#award'
      resources :users, only: %i[show] do
        get '/follow', to: 'users#follow'
        get '/followers', to: 'users#followers'
        get '/following', to: 'users#following'
      end
    end
  end

  scope module: 'admin', constraints: ->(req) { Context.get_context(req) == :admin }, name_path: 'admin', as: 'admin' do
    root to: 'submissions#index'
    match '/', to: 'welcome#index', via: :all

    match '/login', to: 'sessions#login', via: %i[post get]
    match '/logout', to: 'sessions#logout', via: %i[post]

    resources :submissions
    resources :posts do
      delete :ignore_post, on: :member
      delete :cleanse_reports, on: :member
    end

    resources :products do
      put :approve, on: :member
      put :reject, on: :member
    end

    resources :feedback_messages, only: %i[index] do
      patch :mark_as_read, on: :member
    end
  end
end

rails/app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: %i[show approve reject]

  def index
  end

  def show
    @product_allergens = Allergen.where(:off_id.in => @product.allergens || []).to_a
    @matching_product = OpenFoodFacts.product(@product.ean)
    @product_matching_allergens = Allergen.where(:off_id.in => @matching_product.allergens || []).to_a
    @allergens_mismatch = @product_allergens.map(&:name) != @product_matching_allergens.map(&:name)
  end

  def approve
    @product.update_attribute(:status, :APPROVED)
    redirect_to admin_submissions_path, notice: 'Product approved'
  end

  def reject
    @product.update_attribute(:status, :REJECTED)
    redirect_to admin_submissions_path, notice: 'Product rejected'
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end
end

rails/app/controllers/user/allergens_controller.rb
class User::AllergensController < UserApplicationController
  def search
    allergens = Allergen.all
    matched_allergens = allergens.select { |allergen| allergen.name.downcase.include?(params[:term].downcase) }.first(10)
    render json: matched_allergens.map { |allergen| { label: allergen.name, value: allergen.off_id } }
  end
end

rails/app/controllers/user/baskets_controller.rb
class User::BasketsController < UserApplicationController
  before_action :authenticate_user!

  def show
    params[:favorites_page] ||= 1
    recommendation_products = RecommendationsApi.paginated_products(current_user, 1, 3) || {}
    @products = Product.where(:_id.in => recommendation_products["products"])
    
    basket_product_ids = current_user.favorites
    favorite_total_pages = (basket_product_ids.count.to_f / 9).ceil
    if params[:favorites_page].to_i > favorite_total_pages
      params[:favorites_page] = favorite_total_pages == 0 ? 1 : favorite_total_pages
    end

    @basket_products = Product.where(:_id.in => basket_product_ids).skip((params[:favorites_page].to_i - 1) * 9).limit(9)
    @basket_total_pages = favorite_total_pages || 1
  end
end

rails/app/controllers/user/chat_bot_controller.rb
class User::ChatBotController < UserApplicationController
  def send_message
    response = ChatBot.send_message(params[:message], session[:thread_id])
    message = { role: 'assistant', message: response }
    render json: message
  end
end

rails/app/controllers/user/diaries_controller.rb
class User::DiariesController < UserApplicationController
  before_action :authenticate_user!

  def index
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    start_of_day = @date.in_time_zone.beginning_of_day
    end_of_day = @date.in_time_zone.end_of_day
    
    date_key = start_of_day.strftime('%Y-%m-%d')
    @diary_products = Diary
                  .where(user_id: current_user.id)
                  .and("products.#{date_key}".to_sym.exists => true)
                  .first
                  .try(:products)
                  .try(:[], date_key) || []
    @products = @diary_products.map do |product|
      current_product = Product.find(product["product_id"])
      product['fats'] = (current_product.fat * product["quantity"] / 100).round(2)
      product['carbs'] = (current_product.carbohydrates * product["quantity"] / 100).round(2)
      product['proteins'] = (current_product.protein * product["quantity"] / 100).round(2)
      product['calories'] = (current_product.calories * product["quantity"] / 100)
      current_product
    end

    @total_calories = @diary_products.sum { |product| product['calories'] }
    @total_fats = @diary_products.sum { |product| product['fats'] }
    @total_carbs = @diary_products.sum { |product| product['carbs'] }
    @total_proteins = @diary_products.sum { |product| product['proteins'] }

    @data = current_user.get_nutritional_stats_last_30_days
  end

  def add_to_user_diary
    product_id = params[:product_id]
    date = Date.parse(params[:date])
   date_key = date.strftime('%Y-%m-%d')

    diary = Diary.where(user_id: current_user.id).first_or_create
    diary.add_product(product_id, date_key, params[:quantity].to_i)
    diary.save
  end

  def remove_from_user_diary
    product_id = params[:product_id]
    date = Date.parse(params[:date])
    date_key = date.strftime('%Y-%m-%d')

    diary = Diary.where(user_id: current_user.id).first
    diary.remove_product(product_id, date_key)
    diary.save
  end

  def modify_user_diary
    product_id = params[:product_id]
    date = Date.parse(params[:date])
    date_key = date.strftime('%Y-%m-%d')

    diary = Diary.where(user_id: current_user.id).first
    diary.modify_product(product_id, date_key, params[:quantity].to_i)
    diary.save
  end

end

rails/app/controllers/user/gridfs_controller.rb
class User::GridfsController < UserApplicationController
  before_action :authenticate_user!, only: [:serve]

  def serve
    filename = params[:path]
    file_extension = params[:format]
    gridfs_path = "#{filename}.#{file_extension}"

    begin
      gridfs_file = Mongoid::GridFS[gridfs_path]
      self.response_body = gridfs_file.data
      self.content_type = gridfs_file.content_type
    rescue
      self.status = :file_not_found
      self.content_type = 'text/plain'
      self.response_body = ''
    end
  end
end

rails/app/controllers/user/hub/hub_controller.rb
class User::Hub::HubController < UserApplicationController
  layout 'user_hub'

  before_action :authenticate_user!, only: [:following]

  def index
    redirect_to action: :following
  end

  def following
    @posts = Post.recommend_following(current_user)
  end

  def for_you
    params[:page] ||= 1
    posts_data = RecommendationsApi.paginated_hub_posts(current_user, params[:page], 10)

    @posts = Post.where(_id: { '$in': posts_data["posts"] })
    @total_pages = posts_data["total_pages"]
  end
  
  def hashtag
    @hashtag = params[:hashtag]
    @posts = Post.where(:hashtags.in => [@hashtag])
                 .top_level
  end
end

rails/app/controllers/user/hub/posts_controller.rb
class User::Hub::PostsController < UserApplicationController
  before_action :authenticate_user!, only: [:new, :create, :award]

  def show
    @post = Post.find(params[:id.to_s]) rescue not_found

    @post.view(current_user) if current_user.present?
    @post.save!

    ensure_chat_initialized
    ChatBot.send_context(@post, session[:thread_id])
  end

  def new
    @response_to = nil
    if params[:response_to].present?
      @response_to = Post.find(params[:response_to]) rescue not_found
    end
  end

  def create
    post = Post.new(author: current_user, title: params[:title], content: params[:content])
    if params[:response_to_id].present?
      post.response_to = Post.find(params[:response_to_id]) rescue not_found
    end
    post.save!

    redirect_to user_hub_post_path(post)
  end

  def report
    post = Post.find(params[:id.to_s]) rescue (head :not_found and return)
    if current_user.present?
      post.report(current_user)
      post.save!
    else
      head :unauthorized and return
    end

    head :no_content
  end

  def award
    post = Post.find(params[:id]) rescue not_found
    post.award(current_user)
    post.author.save!
    post.save!
    current_user.save!

    redirect_to user_hub_post_path(post), notice: 'Post awarded!'
  end
end

rails/app/controllers/user/hub/ratings_controller.rb
class User::Hub::RatingsController < UserApplicationController

  def destroy
    head :unauthorized and return unless current_user.present?

    rating = Rating.find_by(user: current_user, post: Post.find(params[:post_id])) rescue nil
    head :not_found and return unless rating
    rating.destroy!
    head :no_content
  end

  def create
    unless current_user.present?
      render json: { message: "You must be logged in to vote." }, status: :unauthorized and return
    end

    unless params[:vote].present? and %w(upvote downvote).include?(params[:vote].to_s)
      head :bad_request and return
    end

    symbol = { "upvote" => :up_vote, "downvote" => :down_vote }[params[:vote]]

    rating = Rating.find_by(user: current_user, post: Post.find(params[:post_id])) rescue nil
    if rating.present?
      rating.vote = symbol
      rating.save!
      render json: rating, status: :ok and return
    end

    rating = Rating.create!(user: current_user, post: Post.find(params[:post_id]), vote: symbol)
    render json: rating, status: :created
  end
end

rails/app/controllers/user/hub/users_controller.rb
class User::Hub::UsersController < UserApplicationController
  before_action :authenticate_user!, only: %i[follow followers following]

  def show
    @user = User.find(params[:id]) rescue not_found
  end

  def follow
    user = User.find(params[:user_id]) rescue not_found
    if current_user.following?(user)
      current_user.unfollow_and_save!(user)
    else
      current_user.follow_and_save!(user)
    end

    if request.head?
      head :no_content
    else
      redirect_to action: :show, id: user.id
    end
  end

  def followers
    @user = User.find(params[:user_id]) rescue not_found
  end

  def following
    @user = User.find(params[:user_id]) rescue not_found
  end
end

rails/app/controllers/user/notifications_controller.rb
class User::NotificationsController < UserApplicationController
  before_action :authenticate_user!

  def destroy
    @notification = Notification.find(params[:id])
    @notification.destroy!
    head :no_content
  end
end

rails/app/controllers/user/profiles_controller.rb
class User::ProfilesController < UserApplicationController
  layout 'user_profile'
  before_action :authenticate_user!, except: %i[account]
  before_action :set_links

  def show
    render layout: 'user_application'
  end

  def user
    if request.put?
      update_user_profile
    end
  end

  def account
    if current_user.present?
      @login = current_user.login
    elsif params[:login].present? and params[:token].present?
      @login = Login.find(params[:login]) rescue not_found
    else
      redirect_to user_login_path and return;
    end

    @token = params[:token]
    if @token.present? and @login.reset_password_key != @token
      redirect_to user_login_path, alert: "Invalid or expired password reset token" and return
    end
    @allowed_update = (params[:token].present? and @login.reset_password_key == params[:token])

    if request.put?
      if params[:username].present? && params[:username] != @login.username
        begin
          @login.username = params[:username]
          @login.confirmed_username = true
          @login.save!
          redirect_to user_user_profile_path, notice: "Nickname updated", status: :see_other and return
        rescue Mongoid::Errors::Validations => e
          render json: { message: "Username is already used, try again!" }, status: :unauthorized and return
        end
      end

      if params[:password] != params[:password_confirmation]
        render json: { message: 'Password and password confirmation do not match' }, status: :bad_request and return
      end

      unless @allowed_update
        render json: { message: 'Invalid or expired password reset token' }, status: :unauthorized and return
      end

      @login.password = params[:password]
      @login.save!
      if current_user.present?
        redirect_to user_user_profile_path, notice: "Password updated", status: :see_other
      else
        redirect_to user_login_path, notice: "Password updated", status: :see_other
      end
    end
  end

  def dietary_preferences
    @dietary_preferences = User::DIETARY_PREFERENCES_VALUES

    if request.put?
      current_user.allergens_ids = params["allergens[]"]
      current_user.dietary_preferences = params[:dietary_preferences]
      current_user.save!

      render json: { message: 'Dietary preferences updated' }, status: :ok
    end
  end

  def notifications
    @notifications = current_user.notifications.newest_first
  end

  def billing
  end

  def get_plus
    if params[:price].present?
      x = BillingService::Plus.create_checkout_session(current_user, params[:price], billing_user_profile_url)
      redirect_to x[:url], allow_other_host: true
    end
  end

  def cancel_plus
    BillingService::Plus.cancel_subscription(current_user)
    redirect_to billing_user_profile_path, notice: "Subscription cancelled"
  end

  protected

  def set_links
    if current_user.present?
      @links = [{ href: user_user_profile_path, text: "Profile", icon: "account-outline", md: true },
                { href: account_user_profile_path, text: "Account", icon: "lock-outline", md: true },
                { href: dietary_preferences_user_profile_path, text: "Preferences", icon: "food-outline", md: true },
                { href: user_hub_user_path(current_user), text: "Hub page", icon: "forum-outline", md: false },
                { href: notifications_user_profile_path, text: "Notifications", icon: "bell-outline", md: true },
                { href: billing_user_profile_path, text: "Billing", icon: "currency-usd", md: true},
                { href: user_basket_path, text: "Basket", icon: "cart-outline", md: false}]
    else
      @links = []
    end
  end

  private

  def update_user_profile
    if params[:profile_picture].present? || params.dig(:user, :remove_profile_picture) == "true"
      current_user.update_attributes!(user_params.merge(profile_picture: profile_picture_param))
    else
      current_user.update_attributes!(user_params)
    end
    render status: :ok
  rescue
    render status: :unprocessable_entity
  end

  def user_params
    params.permit(:first_name, :last_name, :weight, :height, :city, :country)
  end

  def profile_picture_param
    params.dig(:user, :remove_profile_picture) == "true" ? nil : params[:profile_picture]
  end
end

rails/app/controllers/user/submissions_controller.rb
class User::SubmissionsController < UserApplicationController

  before_action :authenticate_user!

  def index
    @submitted_products = Product.where(submitted_by: current_user)
  end

end

rails/app/views/user/products/create_product.html.haml
.flex.flex-col.size-full.justify-center.items-center.flex.flex-col.mx-auto.p-4
  .flex.flex-col.shadow-lg.bg-white.rounded-lg.p-4.space-y-4.justify-center.items-center
    .text-2xl.font-semibold.mb-4{class: "backdrop-blur-[2px] p-2 rounded-lg"}
      = "Scan a product or enter the product details manually"

    %button#start_scan{ class: "rounded-md p-2 bg-primary-500 text-white flex-row flex justify-center items-center space-x-2" }
      %i.mdi.mdi-barcode-scan.text-2xl
      %span= "Scan Product Barcode"
    .container#camera_form{ style: "position: relative; width: 300px; height: 100px; overflow: hidden;", hidden: true }
      %video#camera{ autoplay: true, style: "position: absolute; top: -30%; left: 0; width: 100%; height: auto; transform: translateY(-30%);" }
    %button#stop_scan{ class: "rounded-md p-2 bg-red-500 text-white mt-2", hidden: true }
      %i.mdi.mdi-barcode-scan-off.text-2xl
      %span= "Stop Scanning"
    = controlled_form create_product_user_products_path, method: :post, class: "flex flex-col justify-center items-center space-y-4", id: "search_product_form" do
      .flex.flex-col.justify-center.items-center.space-y-4{class: "md:flex-row md:space-x-4 md:space-y-0 md:justify-center md:items-center w-full"}
        .flex.flex-col
          %label.text-slate-700
            = "Search product by barcode"
          %input{ type: "text", id: "barcode", name: "ean", class: "rounded-md p-2 border border-slate-300" }
        .text-slate-700.flex.flex-col.items-center.justify-center.mt-4
          = "or"
        .flex.flex-col
          %label.text-slate-700
            = "Search product by name"
          %input{ type: "text", id: "name", name: "name", class: "rounded-md p-2 border border-slate-300" }
      %button{ type: "submit", class: "rounded-md p-2 !bg-primary-500 text-white" }
        = "Search"
:javascript
  document.addEventListener('DOMContentLoaded', function () {
    const startScan = document.getElementById('start_scan');
    const video = document.getElementById('camera_form');
    let scanner;

    startScan.addEventListener('click', function () {
      setTimeout(() => {
        if (!scanner) {
          scanner = new ZXing.BrowserMultiFormatReader();
          scanner.listVideoInputDevices().then((videoInputDevices) => {
            scanner.decodeFromVideoDevice(videoInputDevices[0].deviceId, 'camera', (result, err) => {
              if (result) {
                scanner.stopAsyncDecode();
                scanner.stopContinuousDecode();
                scanner.reset();
                $.ajax({
                  url: "#{search_by_ean_user_products_path}",
                  method: 'GET',
                  data: { ean: result.text }
                }).done((data) => {
                  window.location.href = data.url;
                }).fail((err) => {
                  console.error(err);
                });
              }
              if (err && !(err instanceof ZXing.NotFoundException)) {
                console.error(err);
              }
            });
            video.style.display = 'block';
            stopScan.style.display = 'block';
            startScan.style.display = 'none';
            $('#search_product_form').hide();
          }).catch((err) => {
            console.error(err);
          });
        }
      }, 200);
    });

    const stopScan = document.getElementById('stop_scan');

    stopScan.addEventListener('click', function () {
      if (scanner) {
        scanner.stopAsyncDecode();
        scanner.stopContinuousDecode();
        scanner.reset();
        scanner = null;
        video.style.display = 'none';
        startScan.style.display = 'block';
        $('#search_product_form').show();
        stopScan.style.display = 'none';
      }
    });
  });

rails/app/views/user/products/index.html.haml
.flex.flex-col.px-4.py-8.justify-center.items-center
  .flex.flex-col.justify-center.items-center.w-full.h-full
    .text-2xl.font-bold.mb-6.p-2.text-center.rounded-lg.bg-clip-border.text-gray-700.shadow-md{ class: "backdrop-blur-[2px]"}
      = "Top rated foods"

    .flex.grid.grid-cols-1{ class: "sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-2 xl:grid-cols-3 gap-8" }
      - @top_products.each do |product|
        .col-span-1.sm:col-span-2.md:col-span-1.lg:col-span-1.xl:col-span-1
          = product_card(product)
    - if @top_products.present?
      .flex.flex-wrap.items-center.justify-center.rounded-lg.bg-white.py-2.px-4.my-4
        - if params[:page].to_i > 1
          = link_to user_products_path(page: 1), class: "mx-1 px-2 py-1 text-sm text-primary-500 hover:bg-primary-100 rounded" do
            %i.mdi.mdi-chevron-double-left{title: "First Page"}

        - if params[:page].to_i > 1
          = link_to user_products_path(page: params[:page].to_i - 1), class: "mx-1 px-2 py-1 text-sm text-primary-500 hover:bg-primary-100 rounded" do
            %i.mdi.mdi-chevron-left{title: "Previous Page"}

        - start_page = [params[:page].to_i - 2, 1].max
        - end_page = [start_page + 4, @total_pages].min

        - start_page.upto(end_page) do |page|
          - if page == params[:page].to_i
            %span.mx-1.px-2.py-1.text-sm.font-semibold.text-white.bg-primary-500.rounded= page
          - else
            = link_to user_products_path(page: page), class: "mx-1 px-2 py-1 text-sm text-primary-500 hover:bg-primary-100 rounded" do
              = page

        - if params[:page].to_i < @total_pages
          = link_to user_products_path(page: params[:page].to_i + 1), class: "mx-1 px-2 py-1 text-sm text-primary-500 hover:bg-primary-100 rounded" do
            %i.mdi.mdi-chevron-right{title: "Next Page"}

        - if params[:page].to_i < @total_pages
          = link_to user_products_path(page: @total_pages), class: "mx-1 px-2 py-1 text-sm text-primary-500 hover:bg-primary-100 rounded" do
            %i.mdi.mdi-chevron-double-right{title: "Last Page"}

= render "partials/diary_modal"

:javascript
  $(document).on('click', '[id^="heart-icon"]', function() {
    const heartId = this.id;
    const productId = this.id.replace('heart-icon-', '');
    if ($("#" + heartId).hasClass('mdi-heart')) {
      $.ajax({
        url: 'products/' + productId + '/remove_from_favorites',
        type: 'PATCH',
        success: function(response) {
          $("#" + heartId).removeClass('mdi-heart').addClass('mdi-heart-outline');
        },
        error: function(response) {
          $("#" + heartId).removeClass('mdi-heart-outline').addClass('mdi-heart');
        }
      });
      return;
    }
    
    $.ajax({
      url: 'products/' + productId + '/add_to_favorites',
      type: 'PATCH',
      success: function(response) {
        $("#" + heartId).removeClass('mdi-heart-outline').addClass('mdi-heart');
      },
      error: function(response) {
        $("#" + heartId).removeClass('mdi-heart').addClass('mdi-heart-outline');
      }
    });
  });

rails/app/views/user/products/new.html.haml
.flex.flex-col.justify-start.items-center
    = render "product_form", product: @product

%br

rails/app/views/user/products/products_selection.html.haml
.flex.flex-col.w-full.h-full.items-center.justify-center.space-y-4
  = link_to create_product_user_products_path, class: "bg-primary-500 text-white rounded-lg p-2 mt-4 w-fit flex flex-row justify-center items-center space-x-2" do
    %i.mdi.mdi-arrow-left 
    .text-lg
      Search for another product
  .flex.grid.grid-cols-1{ class: "sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-2 xl:grid-cols-3 gap-8" }
    - @products.each do |product|
      .col-span-1.sm:col-span-2.md:col-span-1.lg:col-span-1.xl:col-span-1
        = link_to create_product_user_products_path(ean: product.ean), method: :post do
          .product-card{class: "hover:shadow-lg transition-transform duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-102"}
            %div{class: 'relative flex w-full z-0 flex-col rounded-xl bg-white bg-clip-border text-gray-700 shadow-lg max-w-[22rem]'}
              %div{class: 'p-6'}
                %div{class: 'flex flex-col items-center justify-center mb-3'}
                  %h5{class: 'block text-2xl antialiased font-medium leading-snug tracking-normal text-primary-900 overflow-hidden whitespace-nowrap text-ellipsis max-w-full'}
                    = product.name
                  %h6{class: 'block text-l antialiased font-medium leading-snug tracking-normal text-gray-400 overflow-hidden whitespace-nowrap'}
                    = product.brand
                  - if product.image_url.present? 
                    = image_tag product.image_url, class: 'w-full h-48 w-48 rounded-lg', style: 'object-fit: contain;'
                %div{class: 'flex items-center justify-center group gap-2 mt-4 pt-3'}
                  = product_info_tag('mdi-fire', 'Calories', product.calories)
                  = product_info_tag('mdi-water', 'Fat', product.fat)
                  = product_info_tag('mdi-barley', 'Carbohydrates', product.carbohydrates)
                  = product_info_tag('mdi-food-drumstick', 'Protein', product.protein)

          - def product_info_tag(icon_class, label, value)
            %span{class: 'rounded-full border p-2 text-gray-900 border-gray-900/5 bg-gray-900/5'}
              %div{class: 'flex flex-row items-center'}
                %i{class: "mdi #{icon_class} mr-1", style: 'font-size: 1rem;'}
                %p{class: 'text-base font-normal leading-relaxed text-primary-900 antialiased gap-1.5'}
                  = value
                    
  .flex.flex-wrap.items-center.justify-center.rounded-lg.bg-white.py-2.px-4.my-4
    - if params[:page].to_i > 1
      = link_to products_selection_user_products_path(name: params[:name], page: 1), class: "mx-1 px-2 py-1 text-sm text-primary-500 hover:bg-primary-100 rounded" do
        %i.mdi.mdi-chevron-double-left{title: "First Page"}

    - if params[:page].to_i > 1
      = link_to products_selection_user_products_path(name: params[:name], page: params[:page].to_i - 1), class: "mx-1 px-2 py-1 text-sm text-primary-500 hover:bg-primary-100 rounded" do
        %i.mdi.mdi-chevron-left{title: "Previous Page"}

    - start_page = [params[:page].to_i - 2, 1].max
    - end_page = [start_page + 4, @total_pages].min

    - start_page.upto(end_page) do |page|
      - if page == params[:page].to_i
        %span.mx-1.px-2.py-1.text-sm.font-semibold.text-white.bg-primary-500.rounded= page
      - else
        = link_to products_selection_user_products_path(name: params[:name], page: page), class: "mx-1 px-2 py-1 text-sm text-primary-500 hover:bg-primary-100 rounded" do
          = page

    - if params[:page].to_i < @total_pages
      = link_to products_selection_user_products_path(name: params[:name], page: params[:page].to_i + 1), class: "mx-1 px-2 py-1 text-sm text-primary-500 hover:bg-primary-100 rounded" do
        %i.mdi.mdi-chevron-right{title: "Next Page"}

    - if params[:page].to_i < @total_pages
      = link_to products_selection_user_products_path(name: params[:name], page: @total_pages), class: "mx-1 px-2 py-1 text-sm text-primary-500 hover:bg-primary-100 rounded" do
        %i.mdi.mdi-chevron-double-right{title: "Last Page"}

%br