rails/config/routes.rb
Rails.application.routes.draw do
  scope module: 'user', constraints: ->(req) { Context.get_context(req) == :user }, name_path: 'user', as: 'user' do
    root to: 'welcome#index'
    match '/', to: 'welcome#index', via: :all
    match '/search', to: 'welcome#search', via: :all
    match '/recommended-products', to: 'welcome#recommended_products', via: :get
    match '/login', to: 'sessions#login', via: %i[post get]
    match '/register', to: 'sessions#register', via: %i[post get]
    get '/auth/:provider/callback', to: 'sessions#create'
    get '/auth/failure', to: 'sessions#failure'
    match '/recover-account', to: 'sessions#recover_account', via: :get
    match '/confirm-email', to: 'sessions#confirm_email', via: :get
    match '/request-password-reset', to: 'sessions#request_password_reset', via: :get
    match '/logout', to: 'sessions#logout', via: :all
    match '/contact', to: 'welcome#contact', via: :post
    match '/chat/send_message', to: 'chat_bot#send_message', via: :post
    match '/add_goal', to: 'welcome#add_goal', via: :post
    match '/update_goal', to: 'welcome#update_goal', via: :post

    resource :profile, only: %i[show index] do
      match :user, on: :collection, via: %i[get put]
      match :account, on: :collection, via: %i[get put]
      match :dietary_preferences, on: :collection, via: %i[get put]
      match :notifications, on: :collection, via: %i[get]
      match :billing, on: :collection, via: %i[get]
      match :get_plus, on: :collection, via: %i[get]
      match :cancel_plus, on: :collection, via: %i[delete]
    end

    resources :notifications, only: %i[destroy]

    resource :basket

    resources :diaries do
      put :remove_from_user_diary, on: :collection
      post :add_to_user_diary, on: :collection
      put :modify_user_diary, on: :collection
    end

    resources :allergens, only: %i[index show] do
      get :search, on: :collection
    end

    resources :products do
      patch :add_to_favorites, on: :member
      patch :remove_from_favorites, on: :member
      match :create_product, on: :collection, via: %i[get post]
      get :products_selection, on: :collection
      get :search_by_ean, on: :collection
      get :search, on: :collection
      resources :reviews
    end

    resources :submissions, only: %i[index show]
    get '/upload/grid/*path', to: 'gridfs#serve'

    namespace :hub do
      get '/', to: 'hub#index'
      get 'following', to: 'hub#following'
      get 'hashtag/:hashtag', to: 'hub#hashtag'
      get 'for_you', to: 'hub#for_you'
      resources :posts, only: %i[show new create]
      post 'posts/:id/report', to: 'posts#report'
      post 'posts/:post_id/rating', to: 'ratings#create'
      delete 'posts/:post_id/rating', to: 'ratings#destroy'
      post 'posts/:id/award', to: 'posts#award'
      resources :users, only: %i[show] do
        get '/follow', to: 'users#follow'
        get '/followers', to: 'users#followers'
        get '/following', to: 'users#following'
      end
    end
  end

  scope module: 'admin', constraints: ->(req) { Context.get_context(req) == :admin }, name_path: 'admin', as: 'admin' do
    root to: 'submissions#index'
    match '/', to: 'welcome#index', via: :all

    match '/login', to: 'sessions#login', via: %i[post get]
    match '/logout', to: 'sessions#logout', via: %i[post]

    resources :submissions
    resources :posts do
      delete :ignore_post, on: :member
      delete :cleanse_reports, on: :member
    end

    resources :products do
      put :approve, on: :member
      put :reject, on: :member
    end

    resources :feedback_messages, only: %i[index] do
      patch :mark_as_read, on: :member
    end
  end
end

rails/app/models/product.rb
require 'set'

class Product
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Attributes::Dynamic
  
  before_save :notify_review

  APPROVED_STATUSES = %i[PENDING APPROVED REJECTED]

  field :ean, type: String, as: :id
  field :brand, type: String
  field :name, type: String
  field :price, type: Float
  field :weight, type: String
  field :allergens, type: Array
  field :vegan, type: Boolean
  field :vegetarian, type: Boolean
  field :ingredients, type: Array
  field :calories, type: Float
  field :fat, type: Float
  field :saturated_fat, type: Float
  field :carbohydrates, type: Float
  field :fiber, type: Float
  field :sugar, type: Float
  field :protein, type: Float
  field :sodium, type: Float
  field :vitamin_A, type: Float
  field :vitamin_C, type: Float
  field :calcium, type: Float
  field :iron, type: Float
  field :status, type: Symbol, default: :PENDING
  field :rating, type: Integer, default: 0
  field :nutriscore, type: String
  field :image_url, type: String
  
  belongs_to :submitted_by, class_name: "User", inverse_of: :submissions

  def self.from_open_food_facts(ean)
    OpenFoodFacts.product(ean)
  end

  def approved?
    status == :APPROVED
  end

  private

  def notify_review
    return unless status != :PENDING

    saved_product = Product.find(id) rescue return
    return unless saved_product.status != status

    Notification.create_product_review_notification!(self)
  end
end

rails/app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: %i[show approve reject]

  def index
  end

  def show
    @product_allergens = Allergen.where(:off_id.in => @product.allergens || []).to_a
    @matching_product = OpenFoodFacts.product(@product.ean)
    @product_matching_allergens = Allergen.where(:off_id.in => @matching_product.allergens || []).to_a
    @allergens_mismatch = @product_allergens.map(&:name) != @product_matching_allergens.map(&:name)
  end

  def approve
    @product.update_attribute(:status, :APPROVED)
    redirect_to admin_submissions_path, notice: 'Product approved'
  end

  def reject
    @product.update_attribute(:status, :REJECTED)
    redirect_to admin_submissions_path, notice: 'Product rejected'
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end
end

rails/app/controllers/user/products_controller.rb
class User::ProductsController < UserApplicationController
  before_action :authenticate_user!, only: %i[ new edit create update destroy ]
  before_action :set_product, only: %i[ show edit update destroy add_to_favorites remove_from_favorites ]
  skip_before_action :verify_authenticity_token, only: %i[ create update ]

  FATS = %i[ fat saturated_fat ].freeze
  CARBOHYDRATES = %i[ carbohydrates fiber sugar ].freeze
  VITAMINS_MINERALS = %i[ vitamin_A vitamin_C calcium ].freeze
  ESSENTIAL_NUTRIENTS = %i[ protein sodium iron ].freeze

  def index
    params[:page] ||= 1
    @top_products = ProductsRecommendation.filter_products_with_aggregation(current_user, 9, (params[:page].to_i - 1) * 9) rescue []
    @total_pages = (Product.where(status: :APPROVED).count.to_f / 9).ceil
  end

  def show
    if @product.status == :PENDING && (current_user.blank? || @product.submitted_by != current_user)
      redirect_to user_products_path and return
    end

    @allergen_names = Allergen.pluck(:_id, :name).to_h

    @product_allergens = Allergen.where(:off_id.in => @product.allergens || [])
    @reviews = Review.where(product_id: @product.id)
    @current_user_review = @reviews.find_by(reviewer_id: current_user.id) rescue nil
    @product_submitter = User.find(@product.submitted_by)
    @user_allergic_to_product = current_user.present? && current_user.allergens_ids.present? && @product.allergens.present? && current_user.allergens_ids.any? { |allergen| @product.allergens.include?(allergen) }

    ensure_chat_initialized
    ChatBot.send_context(@product, session[:thread_id])
  end

  def new
    @product = Product.new
    @product.ean = params[:ean]
    @matching_product = OpenFoodFacts.product(params[:ean])

    if @matching_product.nil?
      respond_to do |format|
        format.json { render json: { message: "The product does not exists." }, status: :unprocessable_entity }
        format.html { redirect_to create_product_user_products_path, notice: "The product does not exists." }
      end

      return
    end

    @product_allergens = Allergen.where(:off_id.in => @matching_product.allergens).to_a
  end

  def edit
    @product_allergens = Allergen.where(:off_id.in => @product.allergens).to_a
  end

  def create_product
    if request.post?
      if params[:ean].present?
        @product = OpenFoodFacts.product(params[:ean])
      else
        redirect_to products_selection_user_products_path(name: params[:name], page: 1), method: :get and return
      end
      redirect_to create_product_user_products_path and return if @product.nil?
      matching_product = Product.find_by(ean: @product.ean) rescue nil
      redirect_to user_product_path(matching_product) and return if matching_product.present? rescue nil
      if @product.present?
        redirect_to new_user_product_path(ean: @product.ean) and return
      else
        redirect_to new_user_product_path(ean: params[:ean]), notice: "Product not found in Open Food Facts database. Please fill in the details manually."
      end
    end
  end

  def products_selection
    response = OpenFoodFacts.search_by_name_list(params[:name], 3, params[:page].to_i)
    @products = response[:products]
    @total_pages = response[:total]
    if @products.blank?
      redirect_to create_product_user_products_path and return
    end
  end

  def create
    new_product_params = product_params
    new_product_params[:ean] = params[:ean]
    new_product_params[:nutriscore] = params[:nutriscore]
    new_product_params[:vegan] = params[:vegan]
    new_product_params[:vegetarian] = params[:vegetarian]
    new_product_params[:allergens] = params[:allergens].presence || []
    new_product_params[:ingredients] = params[:ingredients].split(' ').presence || []
    new_product_params.each { |key, value| new_product_params[key] = value.strip.gsub(/[\n\r]+/, '') if value.is_a?(String) }
    @product = Product.new(new_product_params)
    @product.submitted_by = current_user.id
    
    @matching_product = OpenFoodFacts.product(params[:ean])
    @product.status = :APPROVED if perfect_match?(@product, @matching_product) rescue false

    respond_to do |format|
      if @product.save
        format.html { redirect_to user_product_path(@product.id), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    new_product_params = product_params
    new_product_params[:ean] = params[:ean]
    new_product_params[:nutriscore] = params[:nutriscore]
    new_product_params[:vegan] = params[:vegan]
    new_product_params[:vegetarian] = params[:vegetarian]
    new_product_params[:allergens] = params[:allergens].presence || []
    new_product_params.each { |key, value| new_product_params[key] = value.strip.gsub(/[\n\r]+/, '') if value.is_a?(String) }

    respond_to do |format|
      if @product.update(new_product_params)
        format.html { redirect_to user_submissions_path }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy!

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search
    products = Product.where(name: /#{params[:term]}/i, status: :APPROVED).limit(5)
    products = products.map { |product| { label: product.name, value: "/products/" + product.id.to_s } }
    products << { label: "Can't find what you're searching for? Explore more options here!", value: "/search?query=#{params[:term]}" }
    render json: products
  end

  def search_by_ean
    @product = Product.find_by(ean: params[:ean]) rescue nil
    if @product.present?
      render json: { url: user_product_path(@product.id) } and return
    else
      render json: { url: new_user_product_path(ean: params[:ean]) } and return
    end
  end

  def add_to_favorites
    current_user.favorites << @product.id
    current_user.save!
    render json: { message: 'Product added to favorites' }, status: :ok
  end

  def remove_from_favorites
    current_user.favorites.delete(@product.id)
    current_user.save!
    render json: { message: 'Product removed from favorites' }, status: :ok
  end
  
private

  def perfect_match?(product, matching_product)
    product.name == matching_product.name && product.brand == matching_product.brand && product.weight == matching_product.weight &&
      (product.allergens || []).sort == (matching_product.allergens || []).sort && (product.calories || 0) == (matching_product.calories || 0) && (product.fat || 0) == (matching_product.fat || 0) &&
        (product.saturated_fat || 0) == (matching_product.saturated_fat || 0) && (product.carbohydrates || 0) == (matching_product.carbohydrates || 0) && (product.fiber || 0) == (matching_product.fiber || 0) &&
          (product.sugar || 0) == (matching_product.sugar || 0) && (product.protein || 0) == (matching_product.protein || 0) && (product.sodium || 0) == (matching_product.sodium || 0)

  end

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:brand, :name, :price, :weight, :calories, :fat, :saturated_fat, :carbohydrates, :fiber, :sugar, :protein, :sodium, :vitamin_A, :vitamin_C, :calcium, :iron, allergens: [], ingredients: [])
  end
end

rails/app/views/admin/products/show.html.haml
.flex.flex-col.justify-center.items-center.w-full
	.flex.flex-col.justify-center.items-center.place-self-center.w-full
		%h1.text-3xl.font-semibold.mt-10.overflow-hidden.text-ellipsis.whitespace-nowrap
			= "#{@product.name}"
		%h1.text-xl.font-semibold.mb-8.overflow-hidden.text-ellipsis.whitespace-nowrap
			= "(#{@product.brand} - #{@product.weight})"

	%div.w-full{ class: "md:w-1/2" }
		.flex.flex-row.rounded-lg.bg-slate-50.p-2.justify-between.items-center.mb-2
			%div{ class: "p-2 font-semibold"}= "Price"
			%div{ class: "p-2 text-slate-700"}= @product.price
		.flex.flex-row.rounded-lg.p-2.justify-between.items-center{ class: "bg-slate-50" }
			.flex.flex-row.items-center
				- if @allergens_mismatch.present?
					.i.mdi.mdi-alert-circle.text-2xl.text-red-500
				.p-2.font-semibold= "Allergens"
			- if @product_allergens.present?
				%div{ class: "p-2 text-slate-700"}
					= @product_allergens.map { |allergen| allergen.name }.join(", ")
			- else
				%div{ class: "p-2 text-slate-700"}= "None"
		.text-red-500.text-sm.mb-4.text-right.mb-2.font-semibold
			= @product_matching_allergens.map(&:name).join(", ")	
		.flex.flex-row.rounded-lg.bg-slate-50.p-2.justify-between.items-center.mb-2
			.flex.flex-row.items-center
				- if @product.calories != (@matching_product.calories || 0)
					.i.mdi.mdi-alert-circle.text-2xl.text-red-500
				%div{ class: "p-2 font-semibold"}= "Calories"
			%div{ class: "p-2 text-slate-700 flex flex-row items-center space-x-1"}
				%span
					= @product.calories
				.text-red-500.font-semibold
					(#{@matching_product.calories})
		.grid.gap-4.w-full.mt-4{ class: "md:grid-cols-2" }
			.flex.flex-col.rounded-lg.space-y-2.w-full
				- User::ProductsController::FATS.each do |fat_type|
					.flex.flex-row.rounded-lg.bg-slate-50.p-2.justify-between.items-center.w-full
						.flex.flex-row.items-center
							- if @product.send(fat_type) != (@matching_product.send(fat_type) || 0)
								.i.mdi.mdi-alert-circle.text-2xl.text-red-500
							%div{ class: "p-2 font-semibold"}= "#{fat_type.to_s.humanize}"
						%div{ class: "p-2 text-slate-700 flex flex-row items-center space-x-1"}
							%span
								= @product.send(fat_type) || 0 
							.text-red-500.font-semibold
								(#{@matching_product.send(fat_type) || 0})
			.flex.flex-col.rounded-lg.space-y-2.w-full
				- User::ProductsController::CARBOHYDRATES.each do |carb|
					.flex.flex-row.rounded-lg.bg-slate-50.p-2.justify-between.items-center.w-full
						.flex.flex-row.items-center
							- if @product.send(carb) != (@matching_product.send(carb) || 0)
								.i.mdi.mdi-alert-circle.text-2xl.text-red-500
							%div{ class: "p-2 font-semibold"}= "#{carb.to_s.humanize}"
						%div{ class: "p-2 text-slate-700 flex flex-row items-center space-x-1"}
							%span
								= @product.send(carb) || 0
							.text-red-500.font-semibold
								(#{@matching_product.send(carb) || 0})
		.grid.gap-4.w-full.mt-4{ class: "md:grid-cols-2" }
			.flex.flex-col.rounded-lg.space-y-2.w-full
				- User::ProductsController::ESSENTIAL_NUTRIENTS.each do |nutrient|
					.flex.flex-row.rounded-lg.bg-slate-50.p-2.justify-between.items-center.w-full
						.flex.flex-row.items-center
							- if @product.send(nutrient) != (@matching_product.send(nutrient) || 0)
								.i.mdi.mdi-alert-circle.text-2xl.text-red-500
							%div{ class: "p-2 font-semibold"}= "#{nutrient.to_s.humanize}"
						%div{ class: "p-2 text-slate-700 flex flex-row items-center space-x-1"}
							%span
								= @product.send(nutrient) || 0
							.text-red-500.font-semibold
								(#{@matching_product.send(nutrient) || 0})
			.flex.flex-col.rounded-lg.space-y-2.w-full
				- User::ProductsController::VITAMINS_MINERALS.each do |vitamin_mineral|
					.flex.flex-row.rounded-lg.bg-slate-50.p-2.justify-between.items-center.w-full
						.flex.flex-row.items-center
							- if @product.send(vitamin_mineral) != (@matching_product.send(vitamin_mineral) || 0)
								.i.mdi.mdi-alert-circle.text-2xl.text-red-500
							%div{ class: "p-2 font-semibold"}= "#{vitamin_mineral.to_s.humanize}"
						%div{ class: "p-2 text-slate-700 flex flex-row items-center space-x-1"}
							%span
								= @product.send(vitamin_mineral) || 0
							.text-red-500.font-semibold
								(#{@matching_product.send(vitamin_mineral) || 0})
		.grid.gap-4.w-full.mt-4.grid-cols.2
			.flex.flex-row.justify-center.items-center.w-full.mt-8.space-x-4
				%div.w-full.text-right
					= link_to 'Approve', approve_admin_product_path(@product), class: 'bg-primary-500 text-white py-2 px-4 rounded-lg', method: :put
				%div.w-full
					= link_to 'Reject', reject_admin_product_path(@product), class: 'bg-red-500 text-white py-2 px-4 rounded-lg', method: :put